local function config(module)
    return require("plugins.config." .. module)
end

config("autopairs")
config("barbecue")
config("bufferline")
config("completion")
config("delimiters")
config("dressing")
config("general")
config("gitsigns")
config("goto-preview")
config("highlight-colors")
config("indent-blankline")
config("illuminate")
config("linting")
config("lualine")
config("noice")
config("notify")
config("nvimtree")
config("oil")
config("startup")
config("symbols-outline")
config("telescope")
config("todo-comments")
config("treesitter")

config("lsp")
config("dap")
